### ISSUE TITLE
When I try to tag images I get a invalid times argumetn error. 

### ISSUE THREAD

**Issue by RMHogervorst** [soodoku/clarifai#5] opened 2017-04-06 15:26 UTC
It doesn't matter if I use one or 3 images vector. 

'''
Error in rep(file_paths, len) : invalid 'times' argument

'''

**Comment by soodoku** [comment] 2017-04-06 16:00
Oh! 

Try this: options(stringsAsFactors=FALSE)

and ping me if doesn't fix. I will issue a patch.

**Comment by RMHogervorst** [comment] 2017-04-07 15:33
Hi @soodoku, the option doesn't work.

**Comment by soodoku** [comment] 2017-04-07 15:40
Righto. I had deduced as much as well. Let me circle back quickly on this. Apologies for the frustration.

**Comment by RMHogervorst** [comment] 2017-04-07 15:49
Thanks! Take it easy, this is not work. 

I'm not sure if the implementaion of the API is correct. Because when I check the status of the api it says the images are processed, So is there a callback method or something?  I never thought it would take a lot of time to run the service on a picture.

**Comment by soodoku** [comment] 2017-04-07 15:51
Righto. Thanks! Will investigate.

**Comment by RMHogervorst** [comment] 2017-04-07 15:59
might all be from the updated API?

**Comment by soodoku** [comment] 2017-04-07 15:59
Ya. just loading up the functions etc. now. Will keep you posted.

**Comment by soodoku** [comment] 2017-04-07 16:15
So, young man, can you send me exact thing you ran and what error you encountered.

One of the things I had done is that the return is invisible. So you have to assign to an object. 

If you do tag_images(file_paths), it will show nothing. But if you assign it to an object, you can print the object.
```
 a <- tag_images(file_paths)
a
```
I plan to nuke the invisible return and make it into a simple return.

**Comment by RMHogervorst** [comment] 2017-04-07 16:25
Well, senior data scientist  Gaurav ...

Let me put this in a reproducible example.
```
library(clarifai)
get_token()
# finding local testimages (me mostly)
vectors<- paste0("sample_images/", dir("sample_images/"))
results <- tag_images(file_paths = vectors[1]) # sending one image
comed <- tag_image_urls(img_urls = "https://i.imgur.com/YBx1h5P.jpg") # using the internetversion
```

Both requests are throtled now actually, but still give the error:
`Error in rep(file_paths, len) : invalid 'times' argument`  <- local version
`Error in if (tag$status_code != "OK") { : argument is of length zero` <- url version

**Comment by soodoku** [comment] 2017-04-07 16:26
Thanks much! v. helpful.

**Comment by soodoku** [comment] 2017-04-07 16:30
Dear R, 

Still can't reproduce. So, can you do me one more favor?

Can you do:

```
devtools::install_github("soodoku/clarifai", build_vignettes = TRUE)
```

and try again?

Thanks man

**Comment by soodoku** [comment] 2017-04-07 16:30
just fyi

```
tag_image_urls(img_urls = "https://i.imgur.com/YBx1h5P.jpg")
                           img_url        tags             probs concept_ids
1  https://i.imgur.com/YBx1h5P.jpg     concert 0.996848225593567 ai_v5lDcKZZ
2  https://i.imgur.com/YBx1h5P.jpg       music 0.996590137481689 ai_Fg5fTMwH
3  https://i.imgur.com/YBx1h5P.jpg performance 0.993533134460449 ai_RQ3Kd2W4
4  https://i.imgur.com/YBx1h5P.jpg    musician 0.985229015350342 ai_DlTgnRP9
5  https://i.imgur.com/YBx1h5P.jpg         one 0.981640577316284 ai_07WWJdH5
6  https://i.imgur.com/YBx1h5P.jpg         men  0.97849714756012 ai_78XlSQmC
7  https://i.imgur.com/YBx1h5P.jpg      singer 0.977558970451355 ai_qjVwqdSd
8  https://i.imgur.com/YBx1h5P.jpg    festival 0.967838227748871 ai_D53W8kcc
9  https://i.imgur.com/YBx1h5P.jpg       stage 0.967793345451355 ai_9s3g5LlV
10 https://i.imgur.com/YBx1h5P.jpg      people 0.961571514606476 ai_dnCBJskH
11 https://i.imgur.com/YBx1h5P.jpg       adult 0.952317416667938 ai_HW8xgg72
12 https://i.imgur.com/YBx1h5P.jpg    portrait 0.943275630474091 ai_Wdr6g1zL
13 https://i.imgur.com/YBx1h5P.jpg        band 0.926625907421112 ai_qtgbGd6f
14 https://i.imgur.com/YBx1h5P.jpg    audience 0.923853993415833 ai_RFnkqBVZ
15 https://i.imgur.com/YBx1h5P.jpg         bar 0.919551074504852 ai_bwFWG3nR
16 https://i.imgur.com/YBx1h5P.jpg  recreation 0.915929317474365 ai_bHtkGlBc
17 https://i.imgur.com/YBx1h5P.jpg     theater  0.91128671169281 ai_SQ8t8xl7
18 https://i.imgur.com/YBx1h5P.jpg     indoors 0.910051107406616 ai_lfrts6X0
19 https://i.imgur.com/YBx1h5P.jpg       movie 0.909102082252502 ai_0b71FPFj
20 https://i.imgur.com/YBx1h5P.jpg   nightclub 0.906591355800629 ai_9VVX9bfR
```

**Comment by RMHogervorst** [comment] 2017-04-07 16:37
nope doesn't work

```
Error in if (tag$status_code != "OK") { : argument is of length zero
```

I've tried registering a new application with the general 1.1 but that one also doesn't work.
Also the new get_token() function returns an object.

**Comment by soodoku** [comment] 2017-04-07 16:43
Thanks! I know what that error is but will investigate why it is happening.

May I ask, are you still getting:

```
Error in rep(file_paths, len) : invalid 'times' argument <- local version
```

that error is weirder.

**Comment by RMHogervorst** [comment] 2017-04-07 16:45
yep that one is also still happening

**Comment by RMHogervorst** [comment] 2017-04-07 16:46
I work on a windows 10  64 bit computer. and this is currenlty R 3.2.

**Comment by soodoku** [comment] 2017-04-07 16:48
Can you produce the output of vectors?

```
vectors<- paste0("sample_images/", dir("sample_images/"))
vectors
```

thanks.

**Comment by RMHogervorst** [comment] 2017-04-07 16:51
This is my literal output. 
So its just a character vector or images
[1] "sample_images/1450642039768.jpg"      
[2] "sample_images/IMG_20160508_194755.jpg"
[3] "sample_images/IMG_7523.JPG"

**Comment by soodoku** [comment] 2017-04-07 16:58
Feel free to copy stuff from your R console.

Now, let's try out the next 3 lines of code in the script:

```
# Just changing var. name for ease.
file_paths <- vectors

# you will need to have library(curl) loaded for form_file function to be accessible
query        <- lapply(file_paths, form_file)

# Print our query
query

# Changes names of the list
names(query) <- rep("encoded_image", length(query))

# Print out query
query 
```

**Comment by RMHogervorst** [comment] 2017-04-07 17:35
```
[[1]]
Form file: 1450642039768.jpg 

[[2]]
Form file: IMG_20160508_194755.jpg 

[[3]]
Form file: IMG_7523.JPG 
```
```
query
$encoded_image
Form file: 1450642039768.jpg 

$encoded_image
Form file: IMG_20160508_194755.jpg 

$encoded_image
Form file: IMG_7523.JPG 
```

**Comment by soodoku** [comment] 2017-04-07 18:37
Ok. So we know that your call to clarifai is failing. 

But to confirm, we can try, 
```
clarifai:::clarifai_POST(path="tag/", query)
```

**Comment by RMHogervorst** [comment] 2017-04-08 09:00
that gives me:
```
[1] "Request was throttled."
$detail
[1] "Request was throttled."
```

**Comment by RMHogervorst** [comment] 2017-04-08 09:02
The interesting thing is, that the get_info request does work. So it might be a post thing. I'll investigate

**Comment by soodoku** [comment] 2017-04-08 11:03
Yeah. You may need credits for POST. Anyhow, closing this as it isn't an issue with the package.

**Closed by soodoku** 2017-04-08 11:03 UTC
